### ISSUE TITLE
How do I use this script in Powershell?

### ISSUE THREAD

**Issue by abhijitnandy** [secretGeek/ok-ps#10]
I'm a n00b in Powershell but thought this would be very useful. But how do I include it?
Going to the folder and running 
```
.\Invoke-OKCommand.ps1
```
doesn't do anything.

My Powershell version is 5.1.19041

The only way I could get it to work is to include the contents of the entire file ```Invoke-OKCommand.ps1``` inside my profile file and then having all the other scripts in my ```WindowsPowerShell``` directory.

I'm sure I'm missing something here.

**Comment by secretGeek** [comment]
Great question thanks for asking. The trick is this: you don’t run the script you “dot” it (sometimes called “dot sourcing”). 

That means you run this code:

. .\invoke-okcommand.ps1

That is: a dot followed by a space followed by the name of the file. 

When you “dot source” a script it means that any functions exposed by that script are now available to be used. 

It’s more like what happens when you load a module. (In the next major update to ok-ps I will turn it into a proper module, and then you’ll install the module instead of dot sourcing it.)

Once you’ve dot sourced it you can call the function “ok” and if there is a local file called .ok you will see a pretty printing of it. 

Ideally you would “dot source” the file from your $profile. (Note also that “dot sourcing” the file has the same effect as copying the entire script into your $profile, because when you start up a Powershell script, your $profile is “dot sourced”.)

**Comment by abhijitnandy** [comment]
Sorry for taking such a long time in replying. Your detailed comment helped.

For the benefit of anyone else seeing this, I'm just going to format the 'dot source'-ing command so that the **space after the first dot** is a bit clearer.

Thanks again!

`
. .\Invoke-OKCommand.ps1
`
